// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bsmtHackathon.Data;

#nullable disable

namespace bsmtHackathon.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251219225840_Kurulum1")]
    partial class Kurulum1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("bsmtHackathon.Models.OgrenciProfili", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alerjiler")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaslangicButcesi")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeslenmeTercihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("EkstraNotlar")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KalanButce")
                        .HasColumnType("TEXT");

                    b.Property<string>("MutfakEkipmanlari")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sehir")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OgrenciProfilleri");
                });

            modelBuilder.Entity("bsmtHackathon.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("bsmtHackathon.Models.YemekPlaniDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJsonData")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("YemekPlanlari");
                });
#pragma warning restore 612, 618
        }
    }
}
